### ISSUE TITLE
Add more episodes

### ISSUE THREAD

**Issue by SohamDave08** [brij1823/TMKOC#1]
Hi @brij1823, 
I would like to add more episodes to the json file, let me know how to work on it!

**Comment by brij1823** [comment]
Hey @SohamDave08 , can you please fork the repository and make your changes? I'll merge it to the main :-D

**Comment by SohamDave08** [comment]
On it!

**Comment by brij1823** [comment]
Looking forward to the best ones you add !! :-D

**Comment by brij1823** [comment]
Thank you Soham for the awesome episodes you added :-D , I have merged your request to main and it;s out there for others to see as well !! please add more if you find any! (closing this issue for now)
